"""Core data models for the Napkin Intelligence Flywheel."""

from __future__ import annotations

import enum
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


class DataLayer(enum.Enum):
    """Strict separation of knowledge layers."""
    GLOBAL = "global"       # Napkin IP: patterns, frameworks, generalized insights
    CATEGORY = "category"   # Industry-specific aggregated learnings
    CLIENT = "client"       # Private: brand pages, campaign data, internal notes


class Confidence(enum.Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class FlyweelStage(enum.Enum):
    INGEST = "ingest"
    SYNTHESIZE = "synthesize"
    STORE = "store"
    USE = "use"
    EVALUATE = "evaluate"
    UPDATE = "update"


@dataclass
class Source:
    """A raw data source ingested into the system."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    source_type: str = ""  # cannes, ipa, effies, dad, brand_material, generated
    content: str = ""
    metadata: dict = field(default_factory=dict)
    ingested_at: str = field(default_factory=lambda: datetime.now().isoformat())
    layer: DataLayer = DataLayer.GLOBAL
    client_id: Optional[str] = None


@dataclass
class WikiPage:
    """A structured knowledge page in the synthesis layer."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    path: str = ""          # e.g. "patterns/humour-in-youth-campaigns.md"
    title: str = ""
    content: str = ""
    layer: DataLayer = DataLayer.GLOBAL
    tags: list[str] = field(default_factory=list)
    links: list[str] = field(default_factory=list)  # paths to related pages
    confidence: Confidence = Confidence.MEDIUM
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    updated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    version: int = 1
    source_ids: list[str] = field(default_factory=list)


@dataclass
class Pattern:
    """A generalized creative insight extracted from data."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    insight: str = ""
    category: str = ""      # e.g. "humour", "emotion", "visual"
    vertical: str = ""      # e.g. "energy_drinks", "automotive"
    evidence: list[str] = field(default_factory=list)
    confidence: Confidence = Confidence.MEDIUM
    times_validated: int = 0
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    updated_at: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class EvaluationResult:
    """Result of evaluating a generated output."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    output_id: str = ""
    quality_score: float = 0.0  # 0-1
    usefulness_score: float = 0.0
    novelty_score: float = 0.0
    reusable: bool = False
    feedback: str = ""
    patterns_extracted: list[str] = field(default_factory=list)
    evaluated_at: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class GeneratedOutput:
    """An output generated by an agent."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    agent: str = ""         # strategist, creative, production
    prompt: str = ""
    output: str = ""
    wiki_pages_used: list[str] = field(default_factory=list)
    raw_sources_used: list[str] = field(default_factory=list)
    layer: DataLayer = DataLayer.GLOBAL
    client_id: Optional[str] = None
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    evaluation: Optional[EvaluationResult] = None


@dataclass
class LogEntry:
    """An entry in the flywheel change log."""
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    action: str = ""        # ingest, synthesize, update, lint, write_back
    summary: str = ""
    source: str = ""
    pages_affected: list[str] = field(default_factory=list)
    layer: DataLayer = DataLayer.GLOBAL
    confidence: Confidence = Confidence.MEDIUM
